require 'cgi'
require 'json'
require 'logger'
require 'pp'
require 'singleton'
require 'thread'

require 'aws-sdk-core'
Aws.use_bundled_cert!

require 'ruby-progressbar'
require 'parallel'
require 'term/ansicolor'
require 'diffy'
require 'hashie'

module Miam; end
require 'miam/ext/string_ext'
require 'miam/ext/hash_ext'
require 'miam/logger'
require 'miam/template_helper'
require 'miam/client'
require 'miam/driver'
require 'miam/dsl'
require 'miam/dsl/context'
require 'miam/dsl/context/group'
require 'miam/dsl/context/managed_policy'
require 'miam/dsl/context/role'
require 'miam/dsl/context/user'
require 'miam/dsl/converter'
require 'miam/exporter'
require 'miam/password_manager'
require 'miam/utils'
require 'miam/version'
